apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: auth

spec:
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005
      protocol: TCP
  type: NodePort
  selector:
    app: auth
