apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
  namespace: auth

spec:
  template:
    metadata:
      name: auth
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          # Using a public nginx image temporarily for testing
          image: nginx:alpine
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: auth-cm
            - secretRef:
                name: auth-secret
      imagePullSecrets:
        - name: dockerhub-secret

  replicas: 1
  selector:
    matchLabels:
      app: auth
