apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akkerii/devops1-infra.git
    targetRevision: HEAD
    path: infra
    directory:
      exclude: "*dockerhub-secret.yaml"
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
