apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: auth
spec:
  rules:
    - http:
        paths:
          - path: /auth
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 3005
